using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using SparkAPI.Models;

namespace SparkAPI.Controllers
{
    public class FinesController : ApiController
    {

        /// <summary>
        ///  Retrieve a list of fine objects that meet your criteria (All fields are optional. If no fields are given all items will be retrieved)
        /// </summary>
        /// <param name="member_id">The id of a member associated with a fine</param>
        public ArrayList Get(int? member_id = null)
        {
            FinesPersistence finep = new FinesPersistence();
            finep.addCallField("member_id", member_id, System.Data.SqlDbType.Int, 4);

            return finep.GetAll();
        }

        /// <summary>
        ///  Retrieve the fine object with a specified fine_id
        /// </summary>
        /// <param name="fine_id">ID generated by database upon its creation</param> 
        public Fine Get(int fine_id)
        {
            FinesPersistence finep = new FinesPersistence();
            finep.addCallField("fine_id", fine_id, System.Data.SqlDbType.Int, 4);

            return (Fine)finep.Get();
        }

        /// <summary>
        ///  Create a new fine object
        /// </summary>
        public HttpResponseMessage Post([FromBody]Fine value)
        {
            FinesPersistence finep = new FinesPersistence();
            int id = finep.Save(value, "fine_id");

            if (id != -1)
            {
                value.member_id = id;
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.Created);
                response.Headers.Location = new Uri(Request.RequestUri, String.Format("fine?fine_id={0}", id));
                return response;
            }
            return Request.CreateResponse(HttpStatusCode.BadRequest);
        }

        /// <summary>
        ///  Update an existing fine object with a specified fine_id
        /// </summary>
        /// <param name="fine_id">ID generated by database upon its creation</param>
        public HttpResponseMessage Put(int fine_id, [FromBody]Fine value)
        {
            FinesPersistence finep = new FinesPersistence();
            finep.addCallField("fine_id", fine_id, System.Data.SqlDbType.Int, 4);

            bool recordExisted = finep.Update(value);

            HttpResponseMessage response;
            if (recordExisted)
            {
                response = Request.CreateResponse(HttpStatusCode.NoContent);
            }
            else
            {
                response = Request.CreateResponse(HttpStatusCode.NotFound);
            }
            return response;
        }

        /// <summary>
        ///  Delete the fine object with a specified fine_id
        /// </summary>
        /// <param name="fine_id">ID generated by database upon its creation</param>
        public HttpResponseMessage Delete(int fine_id)
        {
            FinesPersistence finep = new FinesPersistence();
            finep.addCallField("fine_id", fine_id, System.Data.SqlDbType.Int, 4);

            bool recordExisted = finep.Delete();

            HttpResponseMessage response;
            if(recordExisted)
            {
                response = Request.CreateResponse(HttpStatusCode.NoContent);
            }
            else
            {
                response = Request.CreateResponse(HttpStatusCode.NotFound);
            }
            return response;
        }
    }
}